// Music
const song = [
    {
        pictureName: 'ACA LUKAS - MOJ ZIVOT (OFFICIAL VIDEO)',
        songName:'ACA LUKAS - MOJ ZIVOT (OFFICIAL VIDEO)',
        displayName: 'MOJ ZIVOT',
        artistName:'ACA LUKAS',
    },
    {
        pictureName: 'ALEKSANDRA PRIJOVIC - DUGUJES MI DVA ZIVOTA',
        songName:'ALEKSANDRA PRIJOVIC - DUGUJES MI DVA ZIVOTA (UBICE MOG OCA)',
        displayName: 'DUGUJES MI DVA ZIVOTA',
        artistName:'ALEKSANDRA PRIJOVIC',
    },
    {
        pictureName: 'ALORS ON DANSE (Dubdogz Remake)',
        songName:'ALORS ON DANSE (Dubdogz Remake)',
        displayName: 'ALORS ON DANSE',
        artistName:'Dubdogz Remake',
    },
    {
        pictureName: 'ANDREANA CEKIC - SRECO POJAVI SE (OFFICIAL VIDEO)',
        songName:'ANDREANA CEKIC - SRECO POJAVI SE (OFFICIAL VIDEO)',
        displayName: 'SRECO POJAVI SE',
        artistName:'ANDREANA CEKIC',
    },
    {
        pictureName: 'CVIJA - POZIV (OFFICIAL VIDEO)',
        songName:'CVIJA - POZIV (OFFICIAL VIDEO)',
        displayName: 'POZIV',
        artistName:'CVIJA',
    },
    {
        pictureName: 'DARKO LAZIC - A NEKAD JE DOLAZILA STALNO (OFFICIAL VIDEO)',
        songName:'DARKO LAZIC - A NEKAD JE DOLAZILA STALNO (OFFICIAL VIDEO)',
        displayName: 'A NEKAD JE DOLAZILA STALNO',
        artistName:'DARKO LAZIC',
    },
    {
        pictureName: 'Darrell Story - BELLA CIAO (Official Video)',
        songName:'Darrell Story - BELLA CIAO (Official Video)',
        displayName: 'BELLA CIAO',
        artistName:'Darrell Story',
    },
    {
        pictureName: 'DEVITO x TEODORA - VUDU',
        songName:'DEVITO x TEODORA - VUDU',
        displayName: 'VUDU',
        artistName:'DEVITO x TEODORA',
    },
    {
        pictureName: 'Djani - Lutalica (Official Video 2020)',
        songName:'Djani - Lutalica (Official Video 2020)',
        displayName: 'Lutalica',
        artistName:'Djani',
    },
    {
        pictureName: 'DJOMLA KS & ALMA - DRUGARI (OFFICIAL VIDEO)',
        songName:'DJOMLA KS & ALMA - DRUGARI (OFFICIAL VIDEO)',
        displayName: 'DRUGARI',
        artistName:'DJOMLA KS & ALMA',
    },
    {
        pictureName: 'ELENA - HARAKIRI - (OFFICIAL AUDIO)',
        songName:'ELENA - HARAKIRI - (OFFICIAL AUDIO)',
        displayName: 'HARAKIRI',
        artistName:'ELENA',
    },
    {
        pictureName: 'GAZDA PAJA x MARLON BRUTAL - DIZEL (OFFICIAL VIDEO)',
        songName:'GAZDA PAJA x MARLON BRUTAL - DIZEL (OFFICIAL VIDEO)',
        displayName: 'DIZEL',
        artistName:'GAZDA PAJA x MARLON BRUTAL',
    },

    {
        pictureName: 'JELENA KOSTOV x AMAR GILE - PONEKAD (OFFICIAL VIDEO 2018)',
        songName:'JELENA KOSTOV x AMAR GILE - PONEKAD (OFFICIAL VIDEO 2018)',
        displayName: 'PONEKAD',
        artistName:'JELENA KOSTOV x AMAR GILE',
    },
    {
        pictureName: 'Kakvo tijelo Selma ima',
        songName:'Kakvo tijelo Selma ima',
        displayName: 'Kakvo tijelo Selma ima',
        artistName:'SELMA',
    },
    {
        pictureName: 'Kendi - Arapske Pare (Official 4k Video)',
        songName:'Kendi - Arapske Pare (Official 4k Video)',
        displayName: 'Arapske Pare',
        artistName:'Kendi',
    },
    {
        pictureName: 'Krankšvester - Gaber (Official Video)',
        songName:'Krankšvester - Gaber (Official Video)',
        displayName: 'Gaber',
        artistName:'Krankšvester',
    },
    {
        pictureName: 'Ludi Srbi X Mimi Mercedez - Beli Veš Na 90',
        songName:'Ludi Srbi X Mimi Mercedez - Beli Veš Na 90',
        displayName: 'Beli Veš Na 90',
        artistName:'Ludi Srbi X Mimi Mercedez',
    },
    {
        pictureName: 'MC STOJAN X HURRICANE - TUTURUTU (OFFICIAL VIDEO)',
        songName:'MC STOJAN X HURRICANE - TUTURUTU (OFFICIAL VIDEO)',
        displayName: 'TUTURUTU',
        artistName:'MC STOJAN X HURRICANE',
    },
    {
        pictureName: 'MILAN STANKOVIC X JALA BRAT & BUBA CORELLI - PABLO',
        songName:'MILAN STANKOVIC X JALA BRAT & BUBA CORELLI - PABLO',
        displayName: 'PABLO',
        artistName:'MILAN STANKOVIC X JALA BRAT & BUBA CORELLI',
    },
    {
        pictureName: 'MR. SHARAN x ANDREANA ČEKIĆ - KRALJEVI FALŠA (OFFICIAL VIDEO)',
        songName:'MR. SHARAN x ANDREANA ČEKIĆ - KRALJEVI FALŠA (OFFICIAL VIDEO)',
        displayName: 'KRALJEVI FALŠA',
        artistName:'MR. SHARAN x ANDREANA ČEKIĆ',
    },
    {
        pictureName: 'Nenad Manojlovic - Sad milujes nekog drugog (orkestar Vlade Vrcinca)',
        songName:'Nenad Manojlovic - Sad milujes nekog drugog (orkestar Vlade Vrcinca)',
        displayName: 'Sad milujes nekog drugog',
        artistName:'Nenad Manojlovic',
    },
    {
        pictureName: 'NIKOLIJA - O BIVŠIMA (OFFICIAL VIDEO)',
        songName:'NIKOLIJA - O BIVŠIMA (OFFICIAL VIDEO)',
        displayName: 'O BIVŠIMA',
        artistName:'NIKOLIJA',
    },
    {
        pictureName: 'RADE KOSMAJAC - SVE ĆU DATI KUĆU KONJE - SOBA ZA PLAKANJE - LIVE',
        songName:'RADE KOSMAJAC - SVE ĆU DATI KUĆU KONJE - SOBA ZA PLAKANJE - LIVE',
        displayName: 'SVE ĆU DATI KUĆU KONJE',
        artistName:'RADE KOSMAJAC',
    },
    {
        pictureName: 'RADE KOSMAJAC-TUGO MOJIH DANA.',
        songName:'RADE KOSMAJAC-TUGO MOJIH DANA.',
        displayName: 'TUGO MOJIH DANA.',
        artistName:'RADE KOSMAJAC',
    },
    {
        pictureName: 'RELJA X RASTA - GENGE (OFFICIAL VIDEO)',
        songName:'RELJA X RASTA - GENGE (OFFICIAL VIDEO)',
        displayName: 'GENGE',
        artistName:'RELJA X RASTA',
    },
    {
        pictureName: 'SAMO BOB - CRNI SIN (Official Live Video 2019)',
        songName:'SAMO BOB - CRNI SIN (Official Live Video 2019)',
        displayName: 'CRNI SIN',
        artistName:'SAMO BOB',
    },
    {
        pictureName: 'SAMO BOB - NEMACKI POLICAJCI (OFFICIAL VIDEO)',
        songName:'SAMO BOB - NEMACKI POLICAJCI (OFFICIAL VIDEO)',
        displayName: 'NEMACKI POLICAJCI',
        artistName:'SAMO BOB',
    },
    {
        pictureName: 'SASA KOVACEVIC - Moja Malena (official video) NOVO! 2020',
        songName:'SASA KOVACEVIC - Moja Malena (official video) NOVO! 2020',
        displayName: 'Moja Malena',
        artistName:'SASA KOVACEVIC',
    },
    {
        pictureName: 'SASA KOVACEVIC - Pantera (official video) NOVO! 2020',
        songName:'SASA KOVACEVIC - Pantera (official video) NOVO! 2020',
        displayName: 'Pantera',
        artistName:'SASA KOVACEVIC',
    },
    {
        pictureName: 'Senidah - Mišići (Official Video)',
        songName:'Senidah - Mišići (Official Video)',
        displayName: 'Mišići',
        artistName:'Senidah',
    },
    {
        pictureName: 'SOFI MARINOVA - Lubovni dumi (DJ SAZER REMIX)',
        songName:'SOFI MARINOVA - Lubovni dumi (DJ SAZER REMIX)',
        displayName: 'Lubovni dumi',
        artistName:'SOFI MARINOVA',
    },
    {
        pictureName: 'Srećko Krečar & Andreana Čekić - Opasno me radiš (Official Video) 4K',
        songName:'Srećko Krečar & Andreana Čekić - Opasno me radiš (Official Video) 4K',
        displayName: 'Opasno me radiš',
        artistName:'Srećko Krečar & Andreana Čekić',
    },
    {
        pictureName: 'SUNAJ X EDITA - JUGOSLOVENKA (OFFICIAL COVER VIDEO)',
        songName:'SUNAJ X EDITA - JUGOSLOVENKA (OFFICIAL COVER VIDEO)',
        displayName: 'JUGOSLOVENKA',
        artistName:'SUNAJ X EDITA',
    },
    {
        pictureName: 'TEODORA - GASOLINA (OFFICIAL VIDEO)',
        songName:'TEODORA - GASOLINA (OFFICIAL VIDEO)',
        displayName: 'GASOLINA',
        artistName:'TEODORA',
    },
    {
        pictureName: 'TIJANA eM-ZENA OD SULTANA',
        songName:'TIJANA eM-ZENA OD SULTANA',
        displayName: 'ZENA OD SULTANA',
        artistName:'TIJANA eM',
    },
    {
        pictureName: 'Vanesa - Cetri strane sveta - (Audio 1998)',
        songName:'Vanesa - Cetri strane sveta - (Audio 1998)',
        displayName: 'Cetri strane sveta',
        artistName:'Vanesa',
    },
    {
        pictureName: 'VUK MOB - IDE GAS (EXPLICIT VIDEO)',
        songName:'VUK MOB - IDE GAS (EXPLICIT VIDEO)',
        displayName: 'IDE GAS',
        artistName:'VUK MOB',
    },
    {
        pictureName: 'Камелия - Луда по тебе 1999',
        songName:'Камелия - Луда по тебе 1999',
        displayName: 'Luda po tebe',
        artistName:'Камелия',
    },
   
]